config/routes.rb
Cellar::Application.routes.draw do
  resources :bottles

  resources :boxes

  resources :shelves

  resources :beer_cellars

  devise_for :users
  resources :styles

  resources :beers

  resources :breweries

  get "welcome/index"

  root 'welcome#index'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
    belongs_to :beer
    belongs_to :user
    belongs_to :container, :polymorphic => true
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: [:show, :edit, :update, :destroy]

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.all
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bottle }
      else
        format.html { render action: 'new' }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1
  # PATCH/PUT /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_params
      params.require(:bottle).permit(:user_id, :beer_id, :container_type, :container_id, :acquired, :consumed)
    end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/_bottle.html.erb
<div class="cellar-object-bottle">
<p>
    <strong>Beer:</strong>
    <% if bottle.beer %>
        <%= link_to bottle.beer.name, beer_path(bottle.beer) %>
    <% else %>
        Unknown!
    <% end %>
</p>

<!--
<p>
    <strong>Acquired:</strong>
    <%= bottle.acquired %>
</p>

<p>
    <strong>Consumed:</strong>
    <%= bottle.consumed %>
</p>
-->
</div><%#   /class="cellar-object-bottle" %>

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :beer_id %><br>
    <%= f.number_field :beer_id %>
  </div>
  <div class="field">
    <%= f.label :container_type %><br>
    <%= f.text_field :container_type %>
  </div>
  <div class="field">
    <%= f.label :container_id %><br>
    <%= f.number_field :container_id %>
  </div>
  <div class="field">
    <%= f.label :acquired %><br>
    <%= f.date_select :acquired %>
  </div>
  <div class="field">
    <%= f.label :consumed %><br>
    <%= f.date_select :consumed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<h1>Editing bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<h1>Listing bottles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Beer</th>
      <th>Container type</th>
      <th>Container</th>
      <th>Acquired</th>
      <th>Consumed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bottles.each do |bottle| %>
      <tr>
        <td><%= bottle.user_id %></td>
        <td><%= bottle.beer_id %></td>
        <td><%= bottle.container_type %></td>
        <td><%= bottle.container_id %></td>
        <td><%= bottle.acquired %></td>
        <td><%= bottle.consumed %></td>
        <td><%= link_to 'Show', bottle %></td>
        <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
        <td><%= link_to 'Destroy', bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/new.html.erb
<h1>New bottle</h1>

<%= render 'form' %>

<%= link_to 'Back', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @bottle %>

<hr />

<p>
  <strong>User:</strong>
  <%= @bottle.user_id %>
</p>

<p>
  <strong>Container type:</strong>
  <%= @bottle.container_type %>
</p>

<p>
    <strong>Container:</strong>
    <% if @bottle.container
        if @bottle.container_type == 'BeerCellar'
            linkPath = beer_cellar_path(@bottle.container)
        elsif @bottle.container_type == 'Shelf'
            linkPath = shelf_path(@bottle.container)
        elsif @bottle.container_type == 'Box'
            linkPath = box_path(@bottle.container)
        end
        %>
        <%= link_to @bottle.container.name, linkPath %>
    <% else %>
        (none)
    <% end %>
</p>

<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>