config/routes.rb
Cellar::Application.routes.draw do
  resources :bottles

  resources :boxes

  resources :shelves

  resources :beer_cellars

  devise_for :users
  resources :styles

  resources :beers

  resources :breweries

  get "welcome/index"

  root 'welcome#index'

end

app/models/style.rb
class Style < ActiveRecord::Base
    has_many :children, class_name: "Style", foreign_key: "parent_id"
    belongs_to :parent, class_name: "Style"
    
    has_many :beers
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render action: 'show', status: :created, location: @style }
      else
        format.html { render action: 'new' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :description, :parent_id)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= collection_select(:style, :parent_id, Style.all, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Parent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.name %></td>
        <td><%= style.description %></td>
        <td><% if style.parent %><%= style.parent.name %><% end %></td>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @style.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @style.description %>
</p>

<% if @style.parent %>
<p>
    <strong>Parent:</strong>
    <%= link_to @style.parent.name, style_path(@style.parent) %>
</p>
<% end  # /if @style.parent %>

<p>
    <strong><%= @style.children.length == 1? "Child" : "Children" %></strong>
    <% if @style.children.length == 0 %>(none)<% end %>
</p>
<% if @style.children.length > 0 %>
<ul>
    <% @style.children.each do |childStyle| %>
        <li>
            <%= link_to childStyle.name, style_path(childStyle) %>
        </li>
    <% end  # /@style.children.each do |childStyle| %>
</ul>
<% end  # /if @style.children.length > 0 %>

<p>
    <strong><%= @style.beers.length == 1? "Beer" : "Beers" %></strong>
    <% if @style.beers.length == 0 %>(none)<% end %>
</p>
<% if @style.beers.length > 0 %>
<ul>
    <% @style.beers.each do |beer| %>
        <li>
            <%= link_to beer.name, beer_path(beer) %>
        </li>
    <% end  # /@style.beers.each do |beer| %>
</ul>
<% end  # /if @style.beers.length > 0 %>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>