config/routes.rb
Cellar::Application.routes.draw do
  resources :bottles

  resources :boxes

  resources :shelves

  resources :beer_cellars

  devise_for :users
  resources :styles

  resources :beers

  resources :breweries

  get "welcome/index"

  root 'welcome#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
    belongs_to :brewery
    validates :brewery, presence: true

    belongs_to :style
    validates :style, presence: true
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :abv, :ibu, :type, :released, :best_after, :best_before, :brewery_id, :style_id, :parent_id)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :ibu %><br>
    <%= f.number_field :ibu %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="field">
    <%= f.label :released %><br>
    <%= f.date_select :released %>
  </div>
  <div class="field">
    <%= f.label :best_after %><br>
    <%= f.number_field :best_after %>
  </div>
  <div class="field">
    <%= f.label :best_before %><br>
    <%= f.number_field :best_before %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= collection_select(:beer, :brewery_id, Brewery.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :style_id %><br>
    <%= collection_select(:beer, :style_id, Style.all, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abv</th>
      <th>Ibu</th>
      <th>Type</th>
      <th>Released</th>
      <th>Best after</th>
      <th>Best before</th>
      <th>Brewery</th>
      <th>Style</th>
      <th>Parent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.abv %></td>
        <td><%= beer.ibu %></td>
        <td><%= beer.type %></td>
        <td><%= beer.released %></td>
        <td><%= beer.best_after %></td>
        <td><%= beer.best_before %></td>
        <td><%= beer.brewery_id %></td>
        <td><%= beer.style_id %></td>
        <td><%= beer.parent_id %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @beer.abv %>
</p>

<p>
  <strong>Ibu:</strong>
  <%= @beer.ibu %>
</p>

<p>
  <strong>Type:</strong>
  <%= @beer.type %>
</p>

<p>
  <strong>Released:</strong>
  <%= @beer.released %>
</p>

<p>
  <strong>Best after:</strong>
  <%= @beer.best_after %>
</p>

<p>
  <strong>Best before:</strong>
  <%= @beer.best_before %>
</p>

<p>
    <strong>Brewery:</strong>
    <% if @beer.brewery %>
        <%= link_to @beer.brewery.name, brewery_path(@beer.brewery) %>
    <% elsif @beer.brewery_id %>
        Unknown brewery ID <%= @beer.brewery_id %>
    <% else %>
        None!
    <% end %>
</p>

<p>
    <strong>Style:</strong>
    <% if @beer.style %>
        <%= link_to @beer.style.name, style_path(@beer.style) %>
    <% end  # /if @beer.style %>    
</p>

<p>
  <strong>Parent:</strong>
  <%= @beer.parent_id %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>